package com.yfy.crr;

import java.util.Arrays;
import java.util.List;

/**
 * Created by yfy on 10/21/16.
 */
public class ConcurrentKeywords {
  public static List<String> list = Arrays.asList(
      "synchronized",
      "volatile",

      "BlockingDeque",
      "BlockingQueue",
      "Callable",
      "CompletableFuture.AsynchronousCompletionTask",
      "CompletionService",
      "CompletionStage",
      "ConcurrentMap",
      "ConcurrentNavigableMap",
      "Delayed",
      "Executor",
      "ExecutorService",
      "ForkJoinPool.ForkJoinWorkerThreadFactory",
      "ForkJoinPool.ManagedBlocker",
      "Future",
      "RejectedExecutionHandler",
      "RunnableFuture",
      "RunnableScheduledFuture",
      "ScheduledExecutorService",
      "ScheduledFuture",
      "ThreadFactory",
      "TransferQueue",
      "AbstractExecutorService",
      "ArrayBlockingQueue",
      "CompletableFuture",
      "ConcurrentHashMap",
      "ConcurrentHashMap.KeySetView",
      "ConcurrentLinkedDeque",
      "ConcurrentLinkedQueue",
      "ConcurrentSkipListMap",
      "ConcurrentSkipListSet",
      "CopyOnWriteArrayList",
      "CopyOnWriteArraySet",
      "CountDownLatch",
      "CountedCompleter",
      "CyclicBarrier",
      "DelayQueue",
      "Exchanger",
      "ExecutorCompletionService",
      "Executors",
      "ForkJoinPool",
      "ForkJoinTask",
      "ForkJoinWorkerThread",
      "FutureTask",
      "LinkedBlockingDeque",
      "LinkedBlockingQueue",
      "LinkedTransferQueue",
      "Phaser",
      "PriorityBlockingQueue",
      "RecursiveAction",
      "RecursiveTask",
      "ScheduledThreadPoolExecutor",
      "Semaphore",
      "SynchronousQueue",
      "ThreadLocalRandom",
      "ThreadPoolExecutor",
      "ThreadPoolExecutor.AbortPolicy",
      "ThreadPoolExecutor.CallerRunsPolicy",
      "ThreadPoolExecutor.DiscardOldestPolicy",
      "ThreadPoolExecutor.DiscardPolicy",

      "AtomicBoolean",
      "AtomicInteger",
      "AtomicIntegerArray",
      "AtomicIntegerFieldUpdater",
      "AtomicLong",
      "AtomicLongArray",
      "AtomicLongFieldUpdater",
      "AtomicMarkableReference",
      "AtomicReference",
      "AtomicReferenceArray",
      "AtomicReferenceFieldUpdater",
      "AtomicStampedReference",
      "DoubleAccumulator",
      "DoubleAdder",
      "LongAccumulator",
      "LongAdder",

      "Condition",
      "Lock",
      "ReadWriteLock",
      "AbstractOwnableSynchronizer",
      "AbstractQueuedLongSynchronizer",
      "AbstractQueuedSynchronizer",
      "LockSupport",
      "ReentrantLock",
      "ReentrantReadWriteLock",
      "ReentrantReadWriteLock.ReadLock",
      "ReentrantReadWriteLock.WriteLock",
      "StampedLock");
}
