/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yfy' at '10/20/16 1:21 PM' with Gradle 3.1
 *
 * @author yfy, @date 10/20/16 1:21 PM
 */
public class Library {
  public boolean someLibraryMethod() {
    System.out.println("Hello");
    return true;
  }
}
